#####
# Configure the UF Inputs and Defaults here
#####

[global]
crossServerChecksum = true
restartSplunkWeb = 0
restartSplunkd = 1
stateOnClient = enabled

[serverClass:ufDefault]
whitelist.0 = *

[serverClass:ufDefault:app:org_all_deploymentclient]
[serverClass:ufDefault:app:org_all_forwarder_outputs]

# nix and windows operating system logs
[serverClass:nix]
whitelist.0 = *
machineTypesFilter = linux-*

[serverClass:nix:app:Splunk_TA_nix]

[serverClass:windows]
whitelist.0 = *
machineTypesFilter = windows-*

[serverClass:windows:app:Splunk_TA_windows]

[serverClass:indexers]
whitelist.from_pathname = /opt/splunk/etc/apps/ds_serverclasses/lists/indexerMembers.list

[serverClass:indexers:app:org_all_indexes]
[serverClass:indexers:app:org_all_indexer_base]
