[default]

# SPLUNK INDEXES
# Note, many of these use historical directory names which don't match the
# name of the index. A common mistake is to automatically generate a new
# indexes.conf from the existing names, thereby "losing" (hiding from Splunk)
# the existing data.

[main]
homePath   = volume:primary/defaultdb/db
coldPath   = volume:primary/defaultdb/colddb
thawedPath = $SPLUNK_DB/defaultdb/thaweddb

[history]
homePath   = volume:primary/historydb/db
coldPath   = volume:primary/historydb/colddb
thawedPath = $SPLUNK_DB/historydb/thaweddb

[summary]
homePath   = volume:primary/summarydb/db
coldPath   = volume:primary/summarydb/colddb
thawedPath = $SPLUNK_DB/summarydb/thaweddb

[_internal]
homePath   = volume:primary/_internaldb/db
coldPath   = volume:primary/_internaldb/colddb
thawedPath = $SPLUNK_DB/_internaldb/thaweddb

[_introspection]
homePath   = volume:primary/_introspection/db
coldPath   = volume:primary/_introspection/colddb
thawedPath = $SPLUNK_DB/_introspection/thaweddb

[_telemetry]
homePath   = volume:primary/_telemetry/db
coldPath   = volume:primary/_telemetry/colddb
thawedPath = $SPLUNK_DB/_telemetry/thaweddb

[_audit]
homePath   = volume:primary/audit/db
coldPath   = volume:primary/audit/colddb
thawedPath = $SPLUNK_DB/audit/thaweddb

[_thefishbucket]
homePath   = volume:primary/fishbucket/db
coldPath   = volume:primary/fishbucket/colddb
thawedPath = $SPLUNK_DB/fishbucket/thaweddb

# SPLUNKBASE APP INDEXES

# CUSTOMER INDEXES
[osnix]
homePath=$SPLUNK_DB/$_index_name/db
coldPath=$SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/$_index_name/thaweddb

[osnixscript]
homePath=$SPLUNK_DB/$_index_name/db
coldPath=$SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/$_index_name/thaweddb

[osnixsec]
homePath=$SPLUNK_DB/$_index_name/db
coldPath=$SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/$_index_name/thaweddb

[oswin]
homePath=$SPLUNK_DB/$_index_name/db
coldPath=$SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/$_index_name/thaweddb

[oswinperf]
homePath=$SPLUNK_DB/$_index_name/db
coldPath=$SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/$_index_name/thaweddb

[oswinscript]
homePath=$SPLUNK_DB/$_index_name/db
coldPath=$SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/$_index_name/thaweddb

[oswinsec]
homePath=$SPLUNK_DB/$_index_name/db
coldPath=$SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/$_index_name/thaweddb
