#####
# Configure the UF Inputs and Defaults here
#####

[global]
crossServerChecksum = true
restartSplunkWeb = 0
restartSplunkd = 1
stateOnClient = enabled

# All Management servers (search heads, indexers, heavy forwarders, license manager, monitoring console, cluster manager)
[serverClass:all_mgmt_infra]
whitelist.0 = *
blacklist.from_pathname = /opt/splunk/etc/apps/org_ds_serverclasses/lists/indexerMembers.list

[serverClass:all_mgmt_infra:app:org_all_deploymentclient]
[serverClass:all_mgmt_infra:app:org_all_forwarder_outputs]

# All Search Heads
[serverClass:all_sh_defaults]
whitelist.from_pathname = /opt/splunk/etc/apps/org_ds_serverclasses/lists/searchHeads.list

[serverClass:all_sh_defaults:app:org_all_search_base]

# All Indexers
[serverClass:indexers]
whitelist.from_pathname = /opt/splunk/etc/apps/org_ds_serverclasses/lists/indexerMembers.list

[serverClass:indexers:app:org_all_indexes]
[serverClass:indexers:app:org_all_indexer_base]

# All Forwarders
[serverClass:all_forwarder_defaults]
whitelist.0 = *
blacklist.from_pathname = /opt/splunk/etc/apps/org_ds_serverclasses/lists/indexerMembers.list

[serverClass:all_forwarder_defaults:app:org_all_deploymentclient]
[serverClass:all_forwarder_defaults:app:org_all_forwarder_outputs]

# nix and windows operating system logs
[serverClass:nix]
whitelist.0 = *
machineTypesFilter = linux-*

[serverClass:nix:app:Splunk_TA_nix]

[serverClass:windows]
whitelist.0 = *
machineTypesFilter = windows-*

[serverClass:windows:app:Splunk_TA_windows]

# [serverClass:intermediate_forwarders]
# whitelist.0 = *if*
# whitelist.1 = mc1*

# [serverClass:intermediate_forwarders:app:ap3_all_intermediate_forwarder_pipelines]
# [serverClass:intermediate_forwarders:app:ap3_all_intermediate_forwarder_inputs]
# [serverClass:intermediate_forwarders:app:ap3_all_intermediate_forwarder_limits]